# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-09 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('temporada', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=200)),
                ('descargada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('genero', models.CharField(max_length=200)),
                ('temporadas', models.IntegerField(default=1)),
                ('completada', models.BooleanField(default=False)),
                ('descargada', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='capitulo',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mispeliculas.Serie'),
        ),
    ]
