# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mispeliculas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(default='', upload_to='img'),
        ),
    ]
