# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-17 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mispeliculas', '0002_pelicula_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(upload_to='img'),
        ),
    ]
