# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-24 16:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mispeliculas', '0005_auto_20180124_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
